spring.application.name=library-management

# Allow the server to listen on all network interfaces
server.address=0.0.0.0

#spring.datasource.url=jdbc:mysql://localhost:3306/library_db
#spring.datasource.username=root
#spring.datasource.password=1234

# Tell Spring Boot to use Railway's variables if they exist, otherwise default to local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/library}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Tell Spring Boot to use Railway's dynamic port, or fall back to 8080 locally
server.port=${PORT:8080}


spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true